name: Test workflow
on:
  workflow_dispatch:

jobs:
  test1:
    runs-on: arc-runner-set
    steps:
      - name: Hello world
        run: echo "Hello"
  test2:
    runs-on: arc-runner-set
    steps:
      - name: Hello world
        run: echo "World"
